### ISSUE TITLE
Investigate 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Foorack** [etf-lth/koseki#14]
```bash
May 29 18:02:46 allspark start_production.sh[657665]: [2021-05-29 18:02:46 +0200] [657665] [INFO] Booting worker with pid: 657665
May 29 18:02:46 allspark start_production.sh[657665]: [2021-05-29 18:02:46 +0200] [657665] [ERROR] Exception in worker process
May 29 18:02:46 allspark start_production.sh[657665]: Traceback (most recent call last):
May 29 18:02:46 allspark start_production.sh[657665]:   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
May 29 18:02:46 allspark start_production.sh[657665]:     worker.init_process()
May 29 18:02:46 allspark start_production.sh[657665]:   File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
May 29 18:02:46 allspark start_production.sh[657665]:     self.load_wsgi()
May 29 18:02:46 allspark start_production.sh[657665]:   File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
May 29 18:02:46 allspark start_production.sh[657665]:     self.wsgi = self.app.wsgi()
May 29 18:02:46 allspark start_production.sh[657665]:   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
May 29 18:02:46 allspark start_production.sh[657665]:     self.callable = self.load()
May 29 18:02:46 allspark start_production.sh[657665]:   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
May 29 18:02:46 allspark start_production.sh[657665]:     return self.load_wsgiapp()
May 29 18:02:46 allspark start_production.sh[657665]:   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
May 29 18:02:46 allspark start_production.sh[657665]:     return util.import_app(self.app_uri)
May 29 18:02:46 allspark start_production.sh[657665]:   File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
May 29 18:02:46 allspark start_production.sh[657665]:     mod = importlib.import_module(module)
May 29 18:02:46 allspark start_production.sh[657665]:   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
May 29 18:02:46 allspark start_production.sh[657665]:     return _bootstrap._gcd_import(name[level:], package, level)
May 29 18:02:46 allspark start_production.sh[657665]:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
May 29 18:02:46 allspark start_production.sh[657665]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
May 29 18:02:46 allspark start_production.sh[657665]:   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
May 29 18:02:46 allspark start_production.sh[657665]:   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
May 29 18:02:46 allspark start_production.sh[657665]:   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
May 29 18:02:46 allspark start_production.sh[657665]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
May 29 18:02:46 allspark start_production.sh[657665]:   File "/srv/koseki/koseki/__init__.py", line 6, in <module>
May 29 18:02:46 allspark start_production.sh[657665]:     from koseki.core import KosekiCore
May 29 18:02:46 allspark start_production.sh[657665]:   File "/srv/koseki/koseki/core.py", line 11, in <module>
May 29 18:02:46 allspark start_production.sh[657665]:     from koseki.auth import KosekiAuth
May 29 18:02:46 allspark start_production.sh[657665]:   File "/srv/koseki/koseki/auth.py", line 8, in <module>
May 29 18:02:46 allspark start_production.sh[657665]:     from koseki.db.storage import Storage
May 29 18:02:46 allspark start_production.sh[657665]:   File "/srv/koseki/koseki/db/storage.py", line 9, in <module>
May 29 18:02:46 allspark start_production.sh[657665]:     from koseki.db.types import Base, Group, Person, PersonGroup
May 29 18:02:46 allspark start_production.sh[657665]:   File "/srv/koseki/koseki/db/types.py", line 67, in <module>
May 29 18:02:46 allspark start_production.sh[657665]:     class Person(Base):
May 29 18:02:46 allspark start_production.sh[657665]:   File "/srv/koseki/koseki/db/types.py", line 102, in Person
May 29 18:02:46 allspark start_production.sh[657665]:     def unpaid_payments(self) -> list[Payment]:
May 29 18:02:46 allspark start_production.sh[657665]: TypeError: 'type' object is not subscriptable
May 29 18:02:46 allspark start_production.sh[657665]: [2021-05-29 18:02:46 +0200] [657665] [INFO] Worker exiting (pid: 657665)
May 29 18:02:46 allspark start_production.sh[657659]: [2021-05-29 18:02:46 +0200] [657659] [INFO] Shutting down: Master
May 29 18:02:46 allspark start_production.sh[657659]: [2021-05-29 18:02:46 +0200] [657659] [INFO] Reason: Worker failed to boot.
May 29 18:02:46 allspark systemd[1]: koseki.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
May 29 18:02:46 allspark systemd[1]: koseki.service: Failed with result 'exit-code'.
May 29 18:02:46 allspark systemd[1]: koseki.service: Scheduled restart job, restart counter is at 5.
May 29 18:02:46 allspark systemd[1]: Stopped Koseki.
```

**Comment by MrRinkana** [comment]
Missing steps to reproduce, we do not observe this anymore - maybe it was fixed? @Foorack

**Comment by Foorack** [comment]
@MrRinkana  It was an error inside unpaid_payments, but I didn't have reproducable instructions back then either. It was just a critical error I noticed.

**Comment by MrRinkana** [comment]
Seems to have been be caused by python 3.8 on prod but 3.9 in dev; `list[Payment] = []` present in unpaid_payments was not valid syntax until [3.9+](https://docs.python.org/3.9/whatsnew/3.9.html#type-hinting-generics-in-standard-collections).

I'll close this as code is valid nowadays and the error is not present in any logs since 2022 (any logs I can find)
